query Filters($where: JSON) {
  colors(where: $where, sort: "name:ASC") {
    name
    id
  }

  materials(where: $where, sort: "name:ASC") {
    name
    id
  }
  sizes(where: $where, sort: "name:ASC") {
    name
    id
  }
  tags(where: $where, sort: "name:ASC") {
    name
    id
  }
}
